### ISSUE TITLE
Getting an error from metro bundler about react-navigation

### ISSUE THREAD

**Issue by yash-atreya** [MengTo/react-native-for-designers#8]
Error:
```
ERROR
17:57
While trying to resolve module `@react-navigation/native` from file `/Users/yashatreya/Desktop/react-native-for-designers/node_modules/react-navigation/src/index.js`, the package `/Users/yashatreya/Desktop/react-native-for-designers/node_modules/@react-navigation/native/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/yashatreya/Desktop/react-native-for-designers/node_modules/@react-navigation/native/lib/module/index.js`. Indeed, none of these files exist:

  * /Users/yashatreya/Desktop/react-native-for-designers/node_modules/@react-navigation/native/lib/module/index.js(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
  * /Users/yashatreya/Desktop/react-native-for-designers/node_modules/@react-navigation/native/lib/module/index.js/index(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
ERROR
17:57
Building JavaScript bundle: error
```

Help would be very much appreciated

**Comment by Madgeniusblink** [comment]
@yash1511  I had the same problem but I fixed it by doing the following
Make sure you install expo app as told in the documentation: 
https://reactnavigation.org/docs/getting-started
then set your AppNavigator.js to what I have below...
the only issue is that mode: "modal" will not work so easily... if you figure it out let me know :)


`import * as React from "react";
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
import HomeScreen from "../screens/HomeScreen";
import SectionScreen from "../screens/SectionScreen";

const Stack = createStackNavigator();

const AppNavigator = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Section" component={SectionScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default AppNavigator;`
